# Use an official Python base image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy your Project 1 script into the container
COPY Judah_Whiddon_project1.py .

# Default command: run Python
ENTRYPOINT ["python", "Judah_Whiddon_project1.py"]

