# you showed us this in class Thursday. it removes some unnecessary python packages.
FROM python:3.12-slim

# create and set a directory inside the container
WORKDIR /app

# placing the Python script into the container
COPY Judah_Whiddon_project1.py .

# Runs the Python script once the container starts
CMD ["python", "Judah_Whiddon_project1.py"]

