# Use Python 3.9 base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy Project 1 code into the container
COPY read_html_table.py .

# Default command to run Project 1 script
ENTRYPOINT ["python", "read_html_table.py"]

