# Standard Python image
FROM python:3.9

# Working directory
WORKDIR /app

# Copied the Python script from project1 
COPY read_html_table.py .

# Default command to read urls
ENTRYPOINT ["python", "read_html_table.py"]
