# use python
FROM python:3.9-slim-buster

# set the working directory to ./app
WORKDIR /app

# copy all the contents into /app
COPY . /app

# run the python program
CMD ["python", "read_html_table.py"]